apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blazor
spec:
  template:
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/dominion-of-light/dol-blazor
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      timeoutSeconds: 600
