name: SDK Release

on:
  release:
    types: [published]
    
jobs:
  Package:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: SetTag
      shell: bash
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: update version in csproj
      uses: Mudlet/xmlstarlet-action@master
      with:
        args: ed --inplace -u "/Project/PropertyGroup/PackageVersion" -v ${{ steps.get_version.outputs.VERSION }} dol-sdk/dol-sdk.csproj
    - name: update release notes
      uses: Mudlet/xmlstarlet-action@master
      with:
        args: ed --inplace -u "/Project/PropertyGroup/PackageReleaseNotes" -v https://github.com/bcolemutech/dol-blazor/releases/tag/${{ steps.get_version.outputs.VERSION }} dol-sdk/dol-sdk.csproj
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: dol-sdk/dol-sdk.csproj
        VERSION_STATIC: ${{ steps.get_version.outputs.VERSION }}
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
      
